# Synapse Cell is bootstrapped (no VC). Sponsorship is not currently solicited;
# commercial licensing covers our cost structure (see COMMERCIAL_LICENSE.md).
# This file is intentionally left empty so the "Sponsor" button does not appear.
